---
title: "Assignment 4"
author: "Arnav Murulidhar"
date: "10/5/2020"
output: html_document
---

``` {r , message = FALSE, echo = FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

``` {r load map, echo = FALSE, results = FALSE}
metro_stops <- st_read(
 "metro.kml")
```

## A map of the neighborhood of Jayanagar in the Indian city of Bangalore

```{r open st, echo = FALSE, results = FALSE, message = FALSE}
 KA_state_plane <- "+proj=lcc +lat_1=12.47278 +lat_2=35.17281 +lat_0=0 +lon_0=82 +x_0=2000000 +y_0=2000000 +a=6377301.243 +b=6356100.228368102 +units=m +no_defs "

bangalore_street_features <- opq(bbox = 'Jayanagar Bangalore KA India') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

bangalore_streets <- bangalore_street_features$osm_lines %>%
  st_transform(crs = KA_state_plane)

ggplot(bangalore_streets) +
  geom_sf() +
  theme_map()
```

``` {r create, echo = FALSE, results = FALSE, message = FALSE }
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```
)

``` {r setup, echo = FALSE, results = FALSE, message = FALSE}
otp_setup(otp = path_otp, dir = path_data, memory =2048)
```

``` {r open in browser, echo = FALSE, results = FALSE, message = FALSE}
otpcon <- otp_connect()
```

``` {r isochromes}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = metro_stops, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = KA_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = metro_stops, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = KA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()
```

``` {r map isos}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "stamenbw", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = metro_stops) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side-1000, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

## A map of the metro stations in the area and their driving/walking isochromes

``` {r calc comp iso areas}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a metro stop\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a metro stop\n(square km)",
            breaks = breaks <- seq(0, 2500000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()
```

``` {r stacked area}
iso_areas2 <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL)

ggplot(data=iso_areas2, aes(x=fromPlace, y=as.numeric(area), fill=mode)) +
  geom_bar(stat="identity") +
  scale_y_continuous(name = "m^2") +
  scale_x_discrete(name = "Metro Station",
                   labels = c("Banashankari",
                              "RV Road",
                              "Jayanagar",
                              "South End Circle",
                              "Lalbagh")) +
    scale_fill_discrete(name = element_blank(),
                        labels = c("Driving",
                                   "Walking")) +
  theme_bw()


```
